@echo off
chcp 65001 >nul
echo ========================================
echo Windows Post-Install Script (.bat)
echo Generated: 06/09/2026, 16:10
echo ========================================
echo.

:: Check for Administrator privileges
net session >nul 2>&1
if %errorLevel% neq 0 (
    echo ERROR: This script requires Administrator privileges.
    echo Please right-click and select "Run as administrator"
    echo.
    pause
    exit /b 1
)

echo Starting installation process...
echo.
::============================================
:: SOFTWARE INSTALLATION
::============================================
echo.
echo Installing selected software...
echo This may take a while depending on your internet connection.
echo.

:: Web Browsers
echo Installing Web Browsers...
echo   - Google Chrome
winget install --id Google.Chrome -e --silent --accept-package-agreements --accept-source-agreements 2>>errors.log
echo.

:: Productivity
echo Installing Productivity...
echo   - Adobe Acrobat Reader
winget install --id Adobe.Acrobat.Reader.64-bit -e --silent --accept-package-agreements --accept-source-agreements 2>>errors.log
echo.

:: No system configurations selected
echo No system configurations selected.
echo.

::============================================
:: INSTALLATION COMPLETE
::============================================
echo.
echo ========================================
echo Installation Complete!
echo ========================================
echo.
echo If any installations failed, check errors.log
echo.
echo Next steps:
echo   1. Restart your computer if required
echo   2. Log into your installed applications
echo   3. Customize your settings as needed
echo.
echo Generated by Windows Post-Install Generator
echo https://github.com/kaic/win-post-install
echo.
pause
