echo Installerar Google Chrome...
winget install --id Google.Chrome --silent --accept-source-agreements --accept-package-agreements --source winget

echo Installerar Adobe Acrobat Reader...
winget install --id Adobe.Acrobat.Reader.64-bit --silent --accept-source-agreements --accept-package-agreements --source winget
